import './globals.css'
import { Inter } from 'next/font/google'
import Cheader from "@/components/shared/Cheader";
import Cfooter from "@/components/shared/Cfooter";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir='rtl' className='flex flex-col justify-between'>
      <body>
        <Cheader/>
        <main>
          {children}
        </main>
        <Cfooter/>
      </body>
    </html>
  )
}
